Citizen.CreateThread(function()

while true do

 local police1 = AddBlipForCoord(-445.202, 6014.36, 31.7164)
       SetBlipSprite(police1, 60)
       SetBlipDisplay(police1, 4)
       SetBlipScale(police1, 0.9)
	   SetBlipColour(police1, 29)
       SetBlipAsShortRange(police1, true)
       BeginTextCommandSetBlipName("STRING");
       AddTextComponentString("Poste de Police")
       EndTextCommandSetBlipName(police1)
 local police2 = AddBlipForCoord(1854.21, 3685.51, 34.2671)
       SetBlipSprite(police2, 60)
       SetBlipDisplay(police2, 4)
       SetBlipScale(police2, 0.9)
	   SetBlipColour(police2, 29)
       SetBlipAsShortRange(police2, true)
       BeginTextCommandSetBlipName("STRING");
       AddTextComponentString("Poste de Police")
       EndTextCommandSetBlipName(police2)
 local police3 = AddBlipForCoord(642.001, 0.638351, 82.7869)
       SetBlipSprite(police3, 60)
       SetBlipDisplay(police3, 4)
       SetBlipScale(police3, 0.9)
	   SetBlipColour(police3, 29)
       SetBlipAsShortRange(police3, true)
       BeginTextCommandSetBlipName("STRING");
       AddTextComponentString("Poste de Police")
       EndTextCommandSetBlipName(police3)
 local police4 = AddBlipForCoord(-1198.25, -845.297, 19.317)
       SetBlipSprite(police4, 60)
       SetBlipDisplay(police4, 4)
       SetBlipScale(police4, 0.9)
	   SetBlipColour(police4, 29)
       SetBlipAsShortRange(police4, true)
       BeginTextCommandSetBlipName("STRING");
       AddTextComponentString("Poste de Police")
       EndTextCommandSetBlipName(police4)
 local police5 = AddBlipForCoord(436.811, -982.757, 30.6986)
       SetBlipSprite(police5, 60)
       SetBlipDisplay(police5, 4)
       SetBlipScale(police5, 0.9)
	   SetBlipColour(police5, 29)
       SetBlipAsShortRange(police5, true)
       BeginTextCommandSetBlipName("STRING");
       AddTextComponentString("Poste de Police")
       EndTextCommandSetBlipName(police5)
 local police6 = AddBlipForCoord(360.624, -1584.47, 29.2919)
       SetBlipSprite(police6, 60)
       SetBlipDisplay(police6, 4)
       SetBlipScale(police6, 0.9)
	   SetBlipColour(police6, 29)
       SetBlipAsShortRange(police6, true)
       BeginTextCommandSetBlipName("STRING");
       AddTextComponentString("Poste de Police")
       EndTextCommandSetBlipName(police6)
 local police7 = AddBlipForCoord(825.987, -1290.03, 28.2407)
       SetBlipSprite(police7, 60)
       SetBlipDisplay(police7, 4)
       SetBlipScale(police7, 0.9)
	   SetBlipColour(police7, 29)
       SetBlipAsShortRange(police7, true)
       BeginTextCommandSetBlipName("STRING");
       AddTextComponentString("Poste de Police")
       EndTextCommandSetBlipName(police7)
 local fire1 = AddBlipForCoord(215.786, -1642.49, 29.7138)
       SetBlipSprite(fire1, 60)
       SetBlipDisplay(fire1, 4)
       SetBlipScale(fire1, 0.9)
	   SetBlipColour(fire1, 1)
       SetBlipAsShortRange(fire1, true)
       BeginTextCommandSetBlipName("STRING");
       AddTextComponentString("Caserne de Pompier")
       EndTextCommandSetBlipName(fire1)
 local fire2 = AddBlipForCoord(1202.38, -1460.13, 34.7642)
       SetBlipSprite(fire2, 60)
       SetBlipDisplay(fire2, 4)
       SetBlipScale(fire2, 0.9)
	   SetBlipColour(fire2, 1)
       SetBlipAsShortRange(fire2, true)
       BeginTextCommandSetBlipName("STRING");
       AddTextComponentString("Caserne de Pompier")
       EndTextCommandSetBlipName(fire2)
 local fire3 = AddBlipForCoord(-1087.93, -2374.1, 13.9451)
       SetBlipSprite(fire3, 60)
       SetBlipDisplay(fire3, 4)
       SetBlipScale(fire3, 0.9)
	   SetBlipColour(fire3, 1)
       SetBlipAsShortRange(fire3, true)
       BeginTextCommandSetBlipName("STRING");
       AddTextComponentString("Caserne de Pompier")
       EndTextCommandSetBlipName(fire3)
 local fire4 = AddBlipForCoord(-379.942, 6118.73, 31.8456)
       SetBlipSprite(fire4, 60)
       SetBlipDisplay(fire4, 4)
       SetBlipScale(fire4, 0.9)
	   SetBlipColour(fire4, 1)
       SetBlipAsShortRange(fire4, true)
       BeginTextCommandSetBlipName("STRING");
       AddTextComponentString("Caserne de Pompier")
       EndTextCommandSetBlipName(fire4)
 local fire5 = AddBlipForCoord(-635.992, -121.635, 39.0138)
       SetBlipSprite(fire5, 60)
       SetBlipDisplay(fire5, 4)
       SetBlipScale(fire5, 0.9)
	   SetBlipColour(fire5, 1)
       SetBlipAsShortRange(fire5, true)
       BeginTextCommandSetBlipName("STRING");
       AddTextComponentString("Caserne de Pompier")
       EndTextCommandSetBlipName(fire5)	   
 local fire6 = AddBlipForCoord(1697.26, 3585.46, 35.5443)
       SetBlipSprite(fire6, 60)
       SetBlipDisplay(fire6, 4)
       SetBlipScale(fire6, 0.9)
	   SetBlipColour(fire6, 1)
       SetBlipAsShortRange(fire6, true)
       BeginTextCommandSetBlipName("STRING");
       AddTextComponentString("Caserne de Pompier")
       EndTextCommandSetBlipName(fire6)
 local fire7 = AddBlipForCoord(-2113.74, 2831.58, 32.8093)
       SetBlipSprite(fire7, 60)
       SetBlipDisplay(fire7, 4)
       SetBlipScale(fire7, 0.9)
	   SetBlipColour(fire7, 1)
       SetBlipAsShortRange(fire7, true)
       BeginTextCommandSetBlipName("STRING");
       AddTextComponentString("Caserne de Pompier")
       EndTextCommandSetBlipName(fire7)
 local medical1 = AddBlipForCoord(340.464, -1396.31, 32.5092)
       SetBlipSprite(medical1, 61)
       SetBlipDisplay(medical1, 4)
       SetBlipScale(medical1, 0.9)
	   SetBlipColour(medical1, 0)
       SetBlipAsShortRange(medical1, true)
       BeginTextCommandSetBlipName("STRING");
       AddTextComponentString("Centre Médical")
       EndTextCommandSetBlipName(medical1)
 local medical2 = AddBlipForCoord(-450.586, -340.387, 34.5014)
       SetBlipSprite(medical2, 61)
       SetBlipDisplay(medical2, 4)
       SetBlipScale(medical2, 0.9)
	   SetBlipColour(medical2, 0)
       SetBlipAsShortRange(medical2, true)
       BeginTextCommandSetBlipName("STRING");
       AddTextComponentString("Centre Médical")
       EndTextCommandSetBlipName(medical2)
 local medical3 = AddBlipForCoord(1839.74, 3672.0, 34.2767)
       SetBlipSprite(medical3, 61)
       SetBlipDisplay(medical3, 4)
       SetBlipScale(medical3, 0.9)
	   SetBlipColour(medical3, 0)
       SetBlipAsShortRange(medical3, true)
       BeginTextCommandSetBlipName("STRING");
       AddTextComponentString("Centre Médical")
       EndTextCommandSetBlipName(medical3)
 local medical4 = AddBlipForCoord(360.222, -582.222, 28.8212)
       SetBlipSprite(medical4, 61)
       SetBlipDisplay(medical4, 4)
       SetBlipScale(medical4, 0.9)
	   SetBlipColour(medical4, 0)
       SetBlipAsShortRange(medical4, true)
       BeginTextCommandSetBlipName("STRING");
       AddTextComponentString("Centre Médical")
       EndTextCommandSetBlipName(medical4)
 local medical5 = AddBlipForCoord(-243.463, 6327.87, 32.4262)
       SetBlipSprite(medical5, 61)
       SetBlipDisplay(medical5, 4)
       SetBlipScale(medical5, 0.9)
	   SetBlipColour(medical5, 0)
       SetBlipAsShortRange(medical5, true)
       BeginTextCommandSetBlipName("STRING");
       AddTextComponentString("Centre Médical")
       EndTextCommandSetBlipName(medical5)
 local medical6 = AddBlipForCoord(-677.003, 310.929, 83.0841)
       SetBlipSprite(medical6, 61)
       SetBlipDisplay(medical6, 4)
       SetBlipScale(medical6, 0.9)
	   SetBlipColour(medical6, 0)
       SetBlipAsShortRange(medical6, true)
       BeginTextCommandSetBlipName("STRING");
       AddTextComponentString("Centre Médical")
       EndTextCommandSetBlipName(medical6)	   
 local medical7 = AddBlipForCoord(1151.31, -1529.95, 34.9904)
       SetBlipSprite(medical7, 61)
       SetBlipDisplay(medical7, 4)
       SetBlipScale(medical7, 0.9)
	   SetBlipColour(medical7, 0)
       SetBlipAsShortRange(medical7, true)
       BeginTextCommandSetBlipName("STRING");
       AddTextComponentString("Centre Médical")
       EndTextCommandSetBlipName(medical7)
 local medical8 = AddBlipForCoord(-874.614, -308.375, 39.5448)
       SetBlipSprite(medical8, 61)
       SetBlipDisplay(medical8, 4)
       SetBlipScale(medical8, 0.9)
	   SetBlipColour(medical8, 0)
       SetBlipAsShortRange(medical8, true)
       BeginTextCommandSetBlipName("STRING");
       AddTextComponentString("Centre Médical")
       EndTextCommandSetBlipName(medical8)
	   
     return
   end
end)